server {
	listen 3000;
	server_name localhost;

	gzip on;
	gzip_min_length 1000;
	gzip_types text/plain text/xml application/javascript text/css;

	root /usr/share/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	# normal routes
	# serve given url and default to index.html if not found
	# e.g. /, /user and /foo/bar will return index.html

	location / {
		add_header Cache-Control "no-store";
		try_files $uri $uri/index.html /index.html;
	}

	location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico)$ {
		expires 30d;
		access_log off;
		add_header Cache-Control "public";
		try_files $uri =404;
	}
}